version: '2'
services:
    iotubby_nginx:
        image: nginx:latest
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ../.:/code
        links:
            - iotubby_php
        ports:
            - "80:80"
        networks:
            - raspberry_backend

    iotubby_php:
        build:
            context: ..
            dockerfile: docker-dev/php/Dockerfile
        volumes:
            - ../.:/code
        links:
            - iotubby_database
        networks:
            - raspberry_backend

    iotubby_database:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./db/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: raspberry
        networks:
            raspberry_backend:
                aliases:
                    - database

networks:
    raspberry_backend:
        driver: bridge

